### ISSUE TITLE
replication breaks

### ISSUE THREAD

**Issue by bbarclay** [mariadb-corporation/mariadb-community-columnstore-docker#11]
Replication server breaks. with a number of errors, shutting the replication server off when running local directory on the same Storage container. 

Here's how to replicate. Run the replication server. Then try to import anything fast. It just breaks the replication server. My guess is, this is why s3 is useful, because it can handle the throughput, that the io can't handle when trying to replicate anything that is multithreaded import.

**Comment by drrtuy** [comment]
@bbarclay Are you talking about MDB async replication or something else? If you are then I need to highlight that Columnstore don't need replication for the data b/c the cluster evenlydistributes data across dbroots. However MDB needs a replication to have a proper tables meta data description - .frm files. 
There was a bug and a corresponding MCOL in the Jira that crashes async replication in MDB. It was fixed in the latest 5.6.1.

**Comment by drrtuy** [comment]
Something looks wrong in your instllation. I suggest you to ask questions regarding generic usage of MCS in the corresponding [Google group](https://groups.google.com/g/mariadb-columnstore).
