### ISSUE TITLE
Cannot start a stopped container anymore

### ISSUE THREAD

**Issue by topnessman** [mariadb-corporation/mariadb-community-columnstore-docker#2]
Hello,

I followed the instructions on https://hub.docker.com/r/mariadb/columnstore/ and was able to run the column store docker image successfully using command `docker run -d -p 3306:3306 --name mcs_container mariadb/columnstore`. When I run `docker ps` I can see a running container, and I can enter the container and verify that mariadb column store is running.

However, if I use `docker stop <id_from_previous_step>` to stop and container, I couldn't get it started any more using `docker start <id_from_previous_step>`. It is up for maybe 5 seconds, and then immediately exit with status code 0.

I'm very new to Docker, and I've searched lots of articles online, but still got stuck starting a container again. I really appreciate your help if you could provide some advice on how to solve this problem. Thanks!

**Comment by drrtuy** [comment]
The first thing I would do to debug it is to look what container puts into its stdout/stderr outputs using docker logs
https://docs.docker.com/engine/reference/commandline/logs/.

**Comment by pofl** [comment]
I'm having the same issue. Starting the stopped - previously working - container results in this stdout:

```
$ docker start --attach mcs_container
Starting...
StorageManager PID = 15
loading BRM
OK.
Successfully loaded BRM snapshot
Successfully replayed 2 BRM transactions
workernode PID = 29
controllernode PID = 32
PrimProc PID = 35
ExeMgr PID = 91
WriteEngineServer PID = 94
DMLProc PID = 109
DDLProc PID = 112
Starting MariaDB.200812 13:38:05 mysqld_safe Logging to '/var/lib/mysql/cccb2e6c6d21.err'.
200812 13:38:05 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
 SUCCESS!
Monit daemon with PID 11 awakened
```
Exit code is 0

**Comment by mccullya** [comment]
```db             | Starting...
db             | StorageManager PID = 15
db             | loading BRM
db             | OK.
db             | Successfully loaded BRM snapshot
db             | Successfully replayed 0 BRM transactions
db             | workernode PID = 29
db             | controllernode PID = 32
db             | PrimProc PID = 35
db             | ExeMgr PID = 107
db             | WriteEngineServer PID = 110
db             | DMLProc PID = 125
db             | DDLProc PID = 128
db             | Starting MariaDB.200812 15:17:44 mysqld_safe Logging to '/var/lib/mysql/73c3cb46340d.err'.
db             | 200812 15:17:44 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
db             |  SUCCESS!
db             | Monit daemon with PID 11 awakened```

Same story here...

**Comment by mccullya** [comment]
For what its worth, I got it running again by adding `    entrypoint: ""` to my docker-compose (obvs not a fix)

**Comment by I3urny** [comment]
Hi,

`Monit daemon with PID 11 awakened` means that a monit.id file still exists at `/root/.monit.id`. This is because `docker stop` sends a SIGKILL after 10 seconds if the SIGTERM signal did not end the docker process in time (see [docker stop command](https://docs.docker.com/engine/reference/commandline/stop/)). When restarting the container the monit process finds its `.monit.id` file and tries to restart the daemon. It does that successfully and ends with exit code 0. Unfortunately in the docker world this means that the process has finished which is why the container stops.

The solution to this problem is either setting a higher timeout for the docker stop command or mounting your data into volumes and mount those into new containers instead of restarting.

**Comment by I3urny** [comment]
@pofl might be but that is not the way docker containers should behave. A restarted container should have the same behaviour as a newly created container.

Monits wakeup call restarts the process with the PID stored in `/root/.monit.id` but that doesn't necessarily have to be the actual monit process. 
Since you can not guarantee that the monit process will still have the same PID when the container restarts monit might restart a process that is not monit.  

To demonstrate I started 2 containers:
```
[root@4401a1a7ff6f /]# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4340   756 ?        Ss   18:03   0:00 /usr/bin/tini -- docker-entrypoint.sh /bin/sh -c column
root         6  0.0  0.0  14816  3316 ?        S    18:03   0:00 /bin/bash /usr/bin/docker-entrypoint.sh /bin/sh -c colu
root         9  0.1  0.0 197144  2364 ?        Ssl  18:03   0:00 rsyslogd
root        11  0.0  0.1 109660  5416 ?        Sl   18:03   0:00 monit -I
root       415  0.0  0.2 171456  8832 ?        Sl   18:03   0:00 /usr/bin/StorageManager
root       434  0.0  0.6 3255780 25964 ?       Sl   18:03   0:00 /usr/bin/PrimProc
root       438  0.0  0.3 238520 12492 ?        Sl   18:03   0:00 /usr/bin/controllernode
root       439  0.0  0.3 221196 15400 ?        Sl   18:03   0:00 /usr/bin/workernode DBRM_Worker1
root       474  0.0  0.5 246740 22568 ?        Sl   18:03   0:00 /usr/bin/ExeMgr
root       477  0.0  0.9 317808 37056 ?        Sl   18:03   0:00 /usr/bin/WriteEngineServer
root       492  0.0  0.7 271048 31380 ?        Sl   18:04   0:00 /usr/bin/DMLProc
root       495  0.0  0.5 221212 24172 ?        Sl   18:04   0:00 /usr/bin/DDLProc
root       509  0.0  0.1  39216  5316 ?        S    18:04   0:00 /bin/sh /usr/bin/mysqld_safe --datadir=/var/lib/mysql -
mysql      616  0.1  2.5 895704 101180 ?       Sl   18:04   0:00 /usr/sbin/mariadbd --basedir=/usr --datadir=/var/lib/my
root       640  0.0  0.0  14948  3756 pts/0    Ss   18:07   0:00 bash
root       656  0.0  0.0  50436  3932 pts/0    R+   18:08   0:00 ps -aux
```
```
[root@a5632e6fb21d /]# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4340   780 ?        Ss   18:03   0:00 /usr/bin/tini -- docker-entrypoint.sh /bin/sh -c column
root         7  0.0  0.0  14816  3184 ?        S    18:03   0:00 /bin/bash /usr/bin/docker-entrypoint.sh /bin/sh -c colu
root        10  0.2  0.0 197144  2172 ?        Ssl  18:03   0:00 rsyslogd
root        12  0.0  0.1 109660  5544 ?        Sl   18:03   0:00 monit -I
root       395  0.0  0.2 171456  8720 ?        Sl   18:03   0:00 /usr/bin/StorageManager
root       414  0.0  0.6 3255780 26532 ?       Sl   18:03   0:00 /usr/bin/PrimProc
root       417  0.0  0.3 221196 15160 ?        Sl   18:03   0:00 /usr/bin/workernode DBRM_Worker1
root       423  0.0  0.3 238520 12556 ?        Sl   18:03   0:00 /usr/bin/controllernode
root       454  0.0  0.5 246740 22492 ?        Sl   18:03   0:00 /usr/bin/ExeMgr
root       457  0.0  0.9 317808 36864 ?        Sl   18:03   0:00 /usr/bin/WriteEngineServer
root       472  0.0  0.7 271048 31300 ?        Sl   18:03   0:00 /usr/bin/DMLProc
root       475  0.0  0.6 221212 24468 ?        Sl   18:03   0:00 /usr/bin/DDLProc
root       487  0.0  0.1  39216  5400 ?        S    18:03   0:00 /bin/sh /usr/bin/mysqld_safe --datadir=/var/lib/mysql -
mysql      596  0.1  2.4 901848 100776 ?       Sl   18:03   0:00 /usr/sbin/mariadbd --basedir=/usr --datadir=/var/lib/my
root       624  0.1  0.0  15068  3736 pts/0    Ss   18:06   0:00 bash
root       643  0.0  0.0  50436  3912 pts/0    R+   18:06   0:00 ps -aux
``` 

As you can see `monit -I` is running as PID 11 in one container and PID 12 in the other. 

I think the easiest way to fix this faulty behaviour in the docker container is to remove `/root/.monit.id` at the beginning of the `exitColumnstore` function in `docker-entrypoint.sh`. A simple `rm /root/.monit.id/`should suffice.

Regarding the volumes, you cannot directly mount your local filesystem into the docker container. If you tried to do that you would probably mount an empty directory into the container where it would expect some files, hence not starting. 
What you have to do is just start your container with *named volumes* if you want an easier time mounting them.
The Dockerfile automatically creates 3 volumes but with random IDs as names. 

`$ docker run -v vol1:/etc/columnstore -v vol2:/var/lib/columnstore -v vol3:/var/lib/mysql mariadb/columnstore`

By doing so a volume - with a name that is easily readable - is created for each path:
```
$ docker volume ls
DRIVER              VOLUME NAME
local               vol1
local               vol2
local               vol3
```

If the container now somehow gets into an unstartable state you can simply create a new container with the above mentioned `docker run` command and you should have all your data available in the new container.

**Comment by I3urny** [comment]
Whoops, I think I got something quite wrong. The PID is **not stored in** `/root/.monit.id`, but in `/var/run/monit.pid`. Sorry for the confusion. 
I'm still convinced that the deletion of the PID file solves your problem. I've created a PR (#6) and pushed my version of the image with the fix included under `bgally/columnstore:1.5` and `bgally/columnstore:latest`.

**Comment by marrocksd** [comment]
Do we have a fix for this yet?

**Comment by pofl** [comment]
@marrocksd kind of, yes. You can't restart a stopped container. But if you use named volumes as per I3urny's instructions it works. You just destroy the container and create a new one whenever you want to "restart". You use volumes to preserver the state and the data that was in the container. But as previously explained you have to use named volumes. This is the command I use to start the container.

```bash
# if the container exists already stop and delete it
docker stop maria
docker rm maria
# then "restart" it
docker run -d \
	--name=maria \
	-p 3306:3306 \
	-v mariadb-data:/var/lib/mysql \
	-v columnstore-data:/var/lib/columnstore \
	-v columnstore-etc:/etc/columnstore \
	mariadb/columnstore
```
